# Generated by Django 5.2.7 on 2025-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_announcement_certificate_department_event_statistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='teacher_files/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
