# Generated by Django 5.2.7 on 2025-11-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_course_image_teacher_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image_url',
            new_name='link_url',
        ),
    ]
