# Generated by Django 5.2.13 on 2026-04-21 07:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import faculty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_rename_image_url_course_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinterestarea',
            name='interest_area',
        ),
        migrations.RemoveField(
            model_name='teacherinterestarea',
            name='teacher',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='announcementregistration',
            options={'ordering': ['-registered_at'], 'verbose_name': 'Announcement Registration', 'verbose_name_plural': 'Announcement Registrations'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date_issued'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='certificaterecipient',
            options={'ordering': ['certificate'], 'verbose_name': 'Certificate Recipient', 'verbose_name_plural': 'Certificate Recipients'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_year'], 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-registered_at'], 'verbose_name': 'Event Registration', 'verbose_name_plural': 'Event Registrations'},
        ),
        migrations.AlterModelOptions(
            name='honoraward',
            options={'ordering': ['-year'], 'verbose_name': 'Honor Award', 'verbose_name_plural': 'Honor Awards'},
        ),
        migrations.AlterModelOptions(
            name='interestarea',
            options={'ordering': ['title'], 'verbose_name': 'Interest Area', 'verbose_name_plural': 'Interest Areas'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['-start_year'], 'verbose_name': 'Research', 'verbose_name_plural': 'Researches'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['semester_n'], 'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'ordering': ['order'], 'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='teachercourse',
            options={'verbose_name': 'Teacher Course', 'verbose_name_plural': 'Teacher Courses'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'Timetable', 'verbose_name_plural': 'Timetables'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-end_year'], 'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experiences'},
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='file_url',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='types',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='interestarea',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='research',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='date',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='statistics_name',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='faculty.department'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[faculty.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(through='faculty.TeacherCourse', to='faculty.teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='faculty.teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/'),
        ),
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='faculty.department'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='faculty.teacher'),
        ),
        migrations.AddField(
            model_name='honoraward',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='honoraward',
            name='year',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interestarea',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='interest_areas', to='faculty.teacher'),
        ),
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publications/', validators=[faculty.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='statistics',
            name='icon',
            field=models.CharField(blank=True, help_text='Masalan: fa-users, fa-book', max_length=100),
        ),
        migrations.AddField(
            model_name='statistics',
            name='name',
            field=models.CharField(default='Default Statistics', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='role',
            field=models.CharField(choices=[('lecturer', 'Lecturer'), ('assistant', 'Assistant')], default='lecturer', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='year',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='faculty.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='faculty.semester'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='faculty.teacher'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='faculty.event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to='faculty.student'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to='faculty.teacher'),
        ),
        migrations.AlterField(
            model_name='honoraward',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honor_awards', to='faculty.teacher'),
        ),
        migrations.AlterField(
            model_name='interestarea',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='faculty.teacher'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='start_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researches', to='faculty.teacher'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_n',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqam noto'g'ri formatda", regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='teacher_files/', validators=[faculty.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqam noto'g'ri formatda", regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teachers', to='faculty.course'),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='faculty.teacher'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='faculty.teacher'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='faculty.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementregistration',
            unique_together={('announcement', 'teacher', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'teacher', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together={('teacher', 'course', 'year')},
        ),
        migrations.AddConstraint(
            model_name='certificaterecipient',
            constraint=models.UniqueConstraint(fields=('certificate', 'teacher', 'student', 'department'), name='unique_certificate_recipient'),
        ),
        migrations.DeleteModel(
            name='TeacherInterestArea',
        ),
    ]
