# Generated by Django 5.2.13 on 2026-04-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_teacher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('WEB', 'Web Development'), ('DS', 'Data Science'), ('CS', 'Cyber Security')], default='AI', max_length=10),
            preserve_default=False,
        ),
    ]
