# Generated by Django 5.2.13 on 2026-04-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_alter_course_options_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
