# Generated by Django 5.2.13 on 2026-04-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_alter_announcement_options_announcement_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
