# Generated by Django 5.2.13 on 2026-04-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='about_extra',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='hours_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='monday_friday_hours',
            field=models.CharField(default='09:00 AM – 06:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='saturday_hours',
            field=models.CharField(default='10:00 AM – 02:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='sunday_hours',
            field=models.CharField(default='Closed', max_length=100),
        ),
    ]
