# Generated by Django 5.2.13 on 2026-05-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
