# Generated by Django 5.2.13 on 2026-05-09 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_publication_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='faculty.course')),
            ],
        ),
    ]
