# Generated by Django 5.2.13 on 2026-05-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_coursejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('WEB', 'Web Development'), ('DS', 'Data Science'), ('CS', 'Cyber Security')], max_length=10)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('outcome_image', models.ImageField(blank=True, null=True, upload_to='category/')),
            ],
        ),
    ]
