# Generated by Django 5.2.13 on 2026-05-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0016_categorycontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
                ('category_display', models.CharField(max_length=120)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('about_title', models.CharField(default='About This Program', max_length=200)),
                ('about_description', models.TextField(blank=True)),
                ('outcomes_title', models.CharField(default="What You'll Gain", max_length=200)),
                ('outcomes_image', models.ImageField(blank=True, null=True, upload_to='category_pages/outcomes/')),
                ('testimonial_title', models.CharField(default='Testimonials', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='faculty.categorypage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='category_pages/testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='faculty.categorypage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
