# Generated by Django 5.2.13 on 2026-05-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_categorypage_categoryoutcome_categorytestimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
