# Generated by Django 5.2.13 on 2026-05-10 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_event_registration_url_event_slug_event_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('video', 'Video Gallery'), ('photo', 'Photo Gallery'), ('media', 'Media Gallery')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(choices=[('june', 'June'), ('july', 'July'), ('sept', 'September')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='faculty.teacher')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
