# Generated by Django 5.2.13 on 2026-05-15 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0019_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='categorycontent',
            options={'ordering': ['category'], 'verbose_name': 'Category Content', 'verbose_name_plural': 'Category Contents'},
        ),
        migrations.AlterModelOptions(
            name='categoryoutcome',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Category Outcome', 'verbose_name_plural': 'Category Outcomes'},
        ),
        migrations.AlterModelOptions(
            name='categorypage',
            options={'ordering': ['category_display'], 'verbose_name': 'Category Page', 'verbose_name_plural': 'Category Pages'},
        ),
        migrations.AlterModelOptions(
            name='categorytestimonial',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Category Testimonial', 'verbose_name_plural': 'Category Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursejob',
            options={'ordering': ['title'], 'verbose_name': 'Course Job', 'verbose_name_plural': 'Course Jobs'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        
        migrations.AddConstraint(
            model_name='certificaterecipient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('teacher__isnull', False), ('student__isnull', True), ('department__isnull', True)), models.Q(('teacher__isnull', True), ('student__isnull', False), ('department__isnull', True)), models.Q(('teacher__isnull', True), ('student__isnull', True), ('department__isnull', False)), _connector='OR'), name='certificate_exactly_one_recipient'),
        ),
        migrations.AddField(
            model_name='publiceventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_registrations', to='faculty.event'),
        ),
    ]
