# Generated by Django 5.2.13 on 2026-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0020_publiceventregistration_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publiceventregistration',
            options={'ordering': ['-registered_at'], 'verbose_name': 'Public Event Registration', 'verbose_name_plural': 'Public Event Registrations'},
        ),
        
        migrations.AddConstraint(
            model_name='publiceventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='unique_public_event_email_registration'),
        ),
    ]
