# Generated by Django 5.2.13 on 2026-05-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0021_alter_publiceventregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
    ]
