# Generated by Django 5.2.13 on 2026-05-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0023_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
