# Generated by Django 5.2.13 on 2026-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0024_teacher_temporary_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='history_pdf',
            field=models.FileField(blank=True, null=True, upload_to='departments/history/'),
        ),
    ]
