# Generated by Django 5.2.13 on 2026-05-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0026_coursecategory_alter_course_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
