# Generated by Django 5.2.13 on 2026-05-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0028_coursecategory_course_course_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryTestimonial',
        ),
    ]
