# Generated by Django 5.2.13 on 2026-05-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0029_delete_categorytestimonial'),
    ]

    operations = [
     
       
        migrations.DeleteModel(
            name='CategoryOutcome',
        ),
        migrations.DeleteModel(
            name='CategoryPage',
        ),
        
        migrations.DeleteModel(
            name='EventRegistration',
        ),
        migrations.DeleteModel(
            name='PublicEventRegistration',
        ),
    ]