# Generated by Django 5.2.13 on 2026-06-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0030_alter_announcementregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='announcementregistration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='announcementregistration',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='announcementregistration',
            name='student',
        ),
        migrations.RemoveField(
            model_name='announcementregistration',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='CategoryContent',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='AnnouncementRegistration',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
