# Generated by Django 5.2.13 on 2026-06-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0031_alter_announcementregistration_unique_together_and_more'),
    ]

    operations = [
            migrations.RunSQL(
            """
            CREATE TABLE faculty_student (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                first_name VARCHAR(100) NOT NULL,
                last_name VARCHAR(100) NOT NULL,
                `group` VARCHAR(50) NOT NULL,
                enrollment_year INT UNSIGNED NOT NULL
            );
            """,
            reverse_sql="""
            DROP TABLE faculty_student;
            """
        ),
    ]
