# Generated by Django 5.2.13 on 2026-06-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0032_create_student_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
