# Generated by Django 5.2.13 on 2026-06-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0033_remove_student_email_remove_student_phone'),
    ]

    operations = [
                migrations.RunSQL(
            sql="""
                ALTER TABLE faculty_certificaterecipient
                ADD COLUMN student_id BIGINT UNSIGNED NULL AFTER teacher_id;

                CREATE INDEX faculty_certificaterecipient_student_id_idx
                ON faculty_certificaterecipient (student_id);

                ALTER TABLE faculty_certificaterecipient
                ADD CONSTRAINT faculty_certificaterecipient_student_id_fk
                FOREIGN KEY (student_id) REFERENCES faculty_student(id)
                ON DELETE SET NULL;
            """,
            reverse_sql="""
                ALTER TABLE faculty_certificaterecipient
                DROP FOREIGN KEY faculty_certificaterecipient_student_id_fk;
                DROP INDEX faculty_certificaterecipient_student_id_idx
                    ON faculty_certificaterecipient;
                ALTER TABLE faculty_certificaterecipient
                DROP COLUMN student_id;
            """,
        ),
    ]
