# Generated by Django 5.2.13 on 2026-06-05 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0034_fix_certificaterecipient_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='faculty.course')),
            ],
            options={
                'verbose_name': 'Course Resource',
                'verbose_name_plural': 'Course Resources',
                'ordering': ['title'],
            },
        ),
    ]
