# Generated by Django 5.2.13 on 2026-06-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0038_alter_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursejob',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
