# Generated by Django 5.2.13 on 2026-06-22 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0042_courseweek'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseweek',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseweek',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='courseweek',
            constraint=models.UniqueConstraint(fields=('course', 'week_number'), name='unique_course_week'),
        ),
    ]
