# Generated by Django 5.2.13 on 2026-06-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0043_alter_courseweek_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='course',
            name='link_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
