# Generated by Django 5.2.13 on 2026-06-23 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0044_alter_course_options_alter_course_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_criteria', to='faculty.course')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
