# Generated by Django 5.2.13 on 2026-06-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0046_alter_courseitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
