# Generated by Django 5.2.13 on 2026-06-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0048_alter_galleryitem_month_alter_publication_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='practice_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='practice_title',
        ),
    ]
