# Generated by Django 5.2.13 on 2026-06-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0049_remove_course_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('dsc', 'Doctor of Science')], max_length=20, null=True),
        ),
    ]
